sudo: required

notifications:
  email: false

language: node_js
node_js:
  - "10"

cache:
  - yarn

env:
  global:
    - FOO=foo

#services:
#	- docker

before_install:

script:
  - npm install -g expo-cli@2.2.4
  - yarn install

  - expo login -u @EXPO_LOGIN -p @EXPO_PASS

