sudo: required

notifications:
  email: false

language: node_js
node_js:
  - "10"

cache:
  - yarn

env:
  global:
    - FOO=foo

#services:
#	- docker

before_install:
  - npm install -g expo-cli@2.2.4

script:
  - expo publish

